//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 12:39:03 PM SAST 
//


package za.co.enigma.turing.mda.jee.xsd.batch.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the za.co.enigma.turing.mda.jee.xsd.batch.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BatchArtifacts_QNAME = new QName("http://xmlns.jcp.org/xml/ns/javaee", "batch-artifacts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: za.co.enigma.turing.mda.jee.xsd.batch.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BatchArtifacts }
     * 
     */
    public BatchArtifacts createBatchArtifacts() {
        return new BatchArtifacts();
    }

    /**
     * Create an instance of {@link BatchArtifactRef }
     * 
     */
    public BatchArtifactRef createBatchArtifactRef() {
        return new BatchArtifactRef();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BatchArtifacts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.jcp.org/xml/ns/javaee", name = "batch-artifacts")
    public JAXBElement<BatchArtifacts> createBatchArtifacts(BatchArtifacts value) {
        return new JAXBElement<BatchArtifacts>(_BatchArtifacts_QNAME, BatchArtifacts.class, null, value);
    }

}
