//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 12:12:30 PM SAST 
//


package za.co.enigma.turing.mda.jee.xsd.cdi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://xmlns.jcp.org/xml/ns/javaee}interceptors"/>
 *         &lt;element ref="{http://xmlns.jcp.org/xml/ns/javaee}decorators"/>
 *         &lt;element ref="{http://xmlns.jcp.org/xml/ns/javaee}alternatives"/>
 *         &lt;element ref="{http://xmlns.jcp.org/xml/ns/javaee}scan"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *       &lt;attribute name="version" default="1.1">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;pattern value="\.?[0-9]+(\.[0-9]+)*"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="bean-discovery-mode" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="annotated"/>
 *             &lt;enumeration value="all"/>
 *             &lt;enumeration value="none"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interceptorsOrDecoratorsOrAlternatives"
})
@XmlRootElement(name = "beans")
public class Beans {

    @XmlElementRefs({
        @XmlElementRef(name = "scan", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = Scan.class, required = false),
        @XmlElementRef(name = "decorators", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = Decorators.class, required = false),
        @XmlElementRef(name = "interceptors", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = Interceptors.class, required = false),
        @XmlElementRef(name = "alternatives", namespace = "http://xmlns.jcp.org/xml/ns/javaee", type = Alternatives.class, required = false)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> interceptorsOrDecoratorsOrAlternatives;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "bean-discovery-mode", required = true)
    protected String beanDiscoveryMode;

    /**
     * Gets the value of the interceptorsOrDecoratorsOrAlternatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interceptorsOrDecoratorsOrAlternatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterceptorsOrDecoratorsOrAlternatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link Element }
     * {@link Scan }
     * {@link Decorators }
     * {@link Interceptors }
     * {@link Alternatives }
     * 
     * 
     */
    public List<Object> getInterceptorsOrDecoratorsOrAlternatives() {
        if (interceptorsOrDecoratorsOrAlternatives == null) {
            interceptorsOrDecoratorsOrAlternatives = new ArrayList<Object>();
        }
        return this.interceptorsOrDecoratorsOrAlternatives;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.1";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the beanDiscoveryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeanDiscoveryMode() {
        return beanDiscoveryMode;
    }

    /**
     * Sets the value of the beanDiscoveryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeanDiscoveryMode(String value) {
        this.beanDiscoveryMode = value;
    }

}
