//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 12:41:27 PM SAST 
//


package za.co.enigma.turing.mda.jee.xsd.ejb.jar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 
 *         The method-intf element allows a method element to
 *         differentiate between the methods with the same name and
 *         signature that are multiply defined across the home and
 *         component interfaces (e.g, in both an enterprise bean's
 *         remote and local interfaces or in both an enterprise bean's
 *         home and remote interfaces, etc.); the component and web
 *         service endpoint interfaces, and so on. 
 *         
 *         Local applies to the local component interface, local business 
 *         interfaces, and the no-interface view. 
 *         
 *         Remote applies to both remote component interface and the remote 
 *         business interfaces.  
 *         
 *         ServiceEndpoint refers to methods exposed through a web service
 *         endpoint.
 *         
 *         Timer refers to the bean's timeout callback methods.
 *         
 *         MessageEndpoint refers to the methods of a message-driven bean's
 *         message-listener interface.
 *         
 *         LifecycleCallback refers to the PostConstruct and PreDestroy
 *         lifecycle callback methods of a singleton session bean and
 *         to the PostConstruct, PreDestroy, PrePassivate, and PostActivate
 *         lifecycle callback methods of a stateful session bean.
 *         
 *         The method-intf element must be one of the following:
 *         
 *         Home
 *         Remote
 *         LocalHome
 *         Local
 *         ServiceEndpoint
 *         Timer
 *         MessageEndpoint
 *         LifecycleCallback
 *         
 *       
 * 
 * <p>Java class for method-intfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="method-intfType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://xmlns.jcp.org/xml/ns/javaee>string">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "method-intfType")
public class MethodIntfType
    extends String
{


}
