//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 12:41:27 PM SAST 
//


package za.co.enigma.turing.mda.jee.xsd.ejb.jar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for timer-scheduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timer-scheduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="second" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="minute" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="hour" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="day-of-month" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="month" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="day-of-week" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *         &lt;element name="year" type="{http://xmlns.jcp.org/xml/ns/javaee}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timer-scheduleType", propOrder = {
    "second",
    "minute",
    "hour",
    "dayOfMonth",
    "month",
    "dayOfWeek",
    "year"
})
public class TimerScheduleType {

    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String second;
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String minute;
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String hour;
    @XmlElement(name = "day-of-month")
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String dayOfMonth;
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String month;
    @XmlElement(name = "day-of-week")
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String dayOfWeek;
    protected za.co.enigma.turing.mda.jee.xsd.ejb.jar.String year;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the second property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getSecond() {
        return second;
    }

    /**
     * Sets the value of the second property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setSecond(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.second = value;
    }

    /**
     * Gets the value of the minute property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getMinute() {
        return minute;
    }

    /**
     * Sets the value of the minute property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setMinute(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.minute = value;
    }

    /**
     * Gets the value of the hour property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getHour() {
        return hour;
    }

    /**
     * Sets the value of the hour property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setHour(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.hour = value;
    }

    /**
     * Gets the value of the dayOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setDayOfMonth(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.dayOfMonth = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setMonth(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.month = value;
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setDayOfWeek(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.dayOfWeek = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public za.co.enigma.turing.mda.jee.xsd.ejb.jar.String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link za.co.enigma.turing.mda.jee.xsd.ejb.jar.String }
     *     
     */
    public void setYear(za.co.enigma.turing.mda.jee.xsd.ejb.jar.String value) {
        this.year = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
